//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdtdBaiKiemTraGK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TDTDK22CNT2LESSON09DBEntities : DbContext
    {
        public TDTDK22CNT2LESSON09DBEntities()
            : base("name=TDTDK22CNT2LESSON09DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tdtdKhoa> tdtdKhoa { get; set; }
        public virtual DbSet<tdtdSinhVien> tdtdSinhVien { get; set; }
    }
}
