//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdtdBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdtdKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tdtdKhoa()
        {
            this.tdtdSinhVien = new HashSet<tdtdSinhVien>();
        }
    
        public string TdtdMaKH { get; set; }
        public string TdtdTenKH { get; set; }
        public Nullable<bool> TdtdTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tdtdSinhVien> tdtdSinhVien { get; set; }
    }
}
