//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdtdBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdtdSinhVien
    {
        public string TdtdMaSV { get; set; }
        public string TdtdHoSV { get; set; }
        public string TdtdTenSV { get; set; }
        public Nullable<System.DateTime> TdtdNgaySinh { get; set; }
        public Nullable<bool> TdtdGioiTinh { get; set; }
        public string TdtdPhone { get; set; }
        public string TdtdEmail { get; set; }
        public string TdtdMaKH { get; set; }
    
        public virtual tdtdKhoa tdtdKhoa { get; set; }
    }
}
